#!/bin/bash

export KERNEL=linux
export IMAGE=image
export IMG_NAME=bullseye

if [ ! -f ".port" ]; then
  # get random port number
  port=$(date +%N);
  ((port=$port%60000+5525));
  echo "using $port"
  echo -n $port > .port
fi;

port_num=$(cat .port);

qemu-system-x86_64 \
  -kernel bzImage \
  -append "console=ttyS0 root=/dev/sda earlyprintk=serial nokaslr panic=0 panic_on_oops=0 panic_on_warn=0 ro"\
  -hda $IMAGE/${IMG_NAME}.img \
  -net user,hostfwd=tcp::$port_num-:22 -net nic \
  -enable-kvm \
  -nographic \
  -gdb tcp::55432 \
  -m 4G \
  -cpu host \
  -smp 2 \
  -pidfile vm.pid \
  2>&1 | tee vm.log
